# Generated by Django 4.2.7 on 2023-11-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('company', 'Company'), ('employee', 'Employee')], default='user', max_length=20),
        ),
    ]
